version: '3'
services:
    api:
        build:
            context: "../api"
            dockerfile: Dockerfile
        ports:
          - 8080:8080
    ui:
        build:
            context: "../ui"
            dockerfile: Dockerfile
        ports:
          - 80:80
networks:
    frontend:
